name: ${DOCKER_PROJECT_NAME}

services:

  php:
    container_name: ${DOCKER_PROJECT_NAME}_php
    user: ${UID:-1000}:${GID:-1000}
    build: ./.docker/php
    volumes:
      - ./:/var/www/html

  nginx:
    container_name: ${DOCKER_PROJECT_NAME}_nginx
    build: ./.docker/nginx
    ports:
      - '${DOCKER_FORWARDED_80_PORT}:80'
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  mysql:
    container_name: ${DOCKER_PROJECT_NAME}_mysql
    build: ./.docker/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_ROOT_HOST=%"
    volumes:
      - ./:/app
      - db-data:/var/lib/mysql
    ports:
      - "33320:3306"

volumes:
  db-data:
